// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthGroup               string
	AuthGroupPermissions    string
	AuthPermission          string
	AuthUser                string
	AuthUserGroups          string
	AuthUserUserPermissions string
	DjangoAdminLog          string
	DjangoContentType       string
	DjangoMigrations        string
	DjangoSession           string
	MeetupsMeetup           string
	PetsPet                 string
	PetsSpecies             string
}{
	AuthGroup:               "auth_group",
	AuthGroupPermissions:    "auth_group_permissions",
	AuthPermission:          "auth_permission",
	AuthUser:                "auth_user",
	AuthUserGroups:          "auth_user_groups",
	AuthUserUserPermissions: "auth_user_user_permissions",
	DjangoAdminLog:          "django_admin_log",
	DjangoContentType:       "django_content_type",
	DjangoMigrations:        "django_migrations",
	DjangoSession:           "django_session",
	MeetupsMeetup:           "meetups_meetup",
	PetsPet:                 "pets_pet",
	PetsSpecies:             "pets_species",
}
