// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PetsPet is an object representing the database table.
type PetsPet struct {
	ID        int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string `boil:"name" json:"name" toml:"name" yaml:"name"`
	SpeciesID int64  `boil:"species_id" json:"species_id" toml:"species_id" yaml:"species_id"`

	R *petsPetR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L petsPetL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PetsPetColumns = struct {
	ID        string
	Name      string
	SpeciesID string
}{
	ID:        "id",
	Name:      "name",
	SpeciesID: "species_id",
}

var PetsPetTableColumns = struct {
	ID        string
	Name      string
	SpeciesID string
}{
	ID:        "pets_pet.id",
	Name:      "pets_pet.name",
	SpeciesID: "pets_pet.species_id",
}

// Generated where

var PetsPetWhere = struct {
	ID        whereHelperint64
	Name      whereHelperstring
	SpeciesID whereHelperint64
}{
	ID:        whereHelperint64{field: "\"pets_pet\".\"id\""},
	Name:      whereHelperstring{field: "\"pets_pet\".\"name\""},
	SpeciesID: whereHelperint64{field: "\"pets_pet\".\"species_id\""},
}

// PetsPetRels is where relationship names are stored.
var PetsPetRels = struct {
	Specy string
}{
	Specy: "Specy",
}

// petsPetR is where relationships are stored.
type petsPetR struct {
	Specy *PetsSpecy `boil:"Specy" json:"Specy" toml:"Specy" yaml:"Specy"`
}

// NewStruct creates a new relationship struct
func (*petsPetR) NewStruct() *petsPetR {
	return &petsPetR{}
}

// petsPetL is where Load methods for each relationship are stored.
type petsPetL struct{}

var (
	petsPetAllColumns            = []string{"id", "name", "species_id"}
	petsPetColumnsWithoutDefault = []string{"name", "species_id"}
	petsPetColumnsWithDefault    = []string{"id"}
	petsPetPrimaryKeyColumns     = []string{"id"}
	petsPetGeneratedColumns      = []string{}
)

type (
	// PetsPetSlice is an alias for a slice of pointers to PetsPet.
	// This should almost always be used instead of []PetsPet.
	PetsPetSlice []*PetsPet
	// PetsPetHook is the signature for custom PetsPet hook methods
	PetsPetHook func(context.Context, boil.ContextExecutor, *PetsPet) error

	petsPetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	petsPetType                 = reflect.TypeOf(&PetsPet{})
	petsPetMapping              = queries.MakeStructMapping(petsPetType)
	petsPetPrimaryKeyMapping, _ = queries.BindMapping(petsPetType, petsPetMapping, petsPetPrimaryKeyColumns)
	petsPetInsertCacheMut       sync.RWMutex
	petsPetInsertCache          = make(map[string]insertCache)
	petsPetUpdateCacheMut       sync.RWMutex
	petsPetUpdateCache          = make(map[string]updateCache)
	petsPetUpsertCacheMut       sync.RWMutex
	petsPetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var petsPetAfterSelectHooks []PetsPetHook

var petsPetBeforeInsertHooks []PetsPetHook
var petsPetAfterInsertHooks []PetsPetHook

var petsPetBeforeUpdateHooks []PetsPetHook
var petsPetAfterUpdateHooks []PetsPetHook

var petsPetBeforeDeleteHooks []PetsPetHook
var petsPetAfterDeleteHooks []PetsPetHook

var petsPetBeforeUpsertHooks []PetsPetHook
var petsPetAfterUpsertHooks []PetsPetHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PetsPet) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PetsPet) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PetsPet) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PetsPet) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PetsPet) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PetsPet) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PetsPet) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PetsPet) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PetsPet) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsPetAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPetsPetHook registers your hook function for all future operations.
func AddPetsPetHook(hookPoint boil.HookPoint, petsPetHook PetsPetHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		petsPetAfterSelectHooks = append(petsPetAfterSelectHooks, petsPetHook)
	case boil.BeforeInsertHook:
		petsPetBeforeInsertHooks = append(petsPetBeforeInsertHooks, petsPetHook)
	case boil.AfterInsertHook:
		petsPetAfterInsertHooks = append(petsPetAfterInsertHooks, petsPetHook)
	case boil.BeforeUpdateHook:
		petsPetBeforeUpdateHooks = append(petsPetBeforeUpdateHooks, petsPetHook)
	case boil.AfterUpdateHook:
		petsPetAfterUpdateHooks = append(petsPetAfterUpdateHooks, petsPetHook)
	case boil.BeforeDeleteHook:
		petsPetBeforeDeleteHooks = append(petsPetBeforeDeleteHooks, petsPetHook)
	case boil.AfterDeleteHook:
		petsPetAfterDeleteHooks = append(petsPetAfterDeleteHooks, petsPetHook)
	case boil.BeforeUpsertHook:
		petsPetBeforeUpsertHooks = append(petsPetBeforeUpsertHooks, petsPetHook)
	case boil.AfterUpsertHook:
		petsPetAfterUpsertHooks = append(petsPetAfterUpsertHooks, petsPetHook)
	}
}

// One returns a single petsPet record from the query.
func (q petsPetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PetsPet, error) {
	o := &PetsPet{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for pets_pet")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PetsPet records from the query.
func (q petsPetQuery) All(ctx context.Context, exec boil.ContextExecutor) (PetsPetSlice, error) {
	var o []*PetsPet

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PetsPet slice")
	}

	if len(petsPetAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PetsPet records in the query.
func (q petsPetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count pets_pet rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q petsPetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if pets_pet exists")
	}

	return count > 0, nil
}

// Specy pointed to by the foreign key.
func (o *PetsPet) Specy(mods ...qm.QueryMod) petsSpecyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SpeciesID),
	}

	queryMods = append(queryMods, mods...)

	query := PetsSpecies(queryMods...)
	queries.SetFrom(query.Query, "\"pets_species\"")

	return query
}

// LoadSpecy allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (petsPetL) LoadSpecy(ctx context.Context, e boil.ContextExecutor, singular bool, maybePetsPet interface{}, mods queries.Applicator) error {
	var slice []*PetsPet
	var object *PetsPet

	if singular {
		object = maybePetsPet.(*PetsPet)
	} else {
		slice = *maybePetsPet.(*[]*PetsPet)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &petsPetR{}
		}
		args = append(args, object.SpeciesID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &petsPetR{}
			}

			for _, a := range args {
				if a == obj.SpeciesID {
					continue Outer
				}
			}

			args = append(args, obj.SpeciesID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`pets_species`),
		qm.WhereIn(`pets_species.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PetsSpecy")
	}

	var resultSlice []*PetsSpecy
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PetsSpecy")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for pets_species")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for pets_species")
	}

	if len(petsPetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Specy = foreign
		if foreign.R == nil {
			foreign.R = &petsSpecyR{}
		}
		foreign.R.SpecyPetsPets = append(foreign.R.SpecyPetsPets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SpeciesID == foreign.ID {
				local.R.Specy = foreign
				if foreign.R == nil {
					foreign.R = &petsSpecyR{}
				}
				foreign.R.SpecyPetsPets = append(foreign.R.SpecyPetsPets, local)
				break
			}
		}
	}

	return nil
}

// SetSpecy of the petsPet to the related item.
// Sets o.R.Specy to related.
// Adds o to related.R.SpecyPetsPets.
func (o *PetsPet) SetSpecy(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PetsSpecy) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"pets_pet\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"species_id"}),
		strmangle.WhereClause("\"", "\"", 2, petsPetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SpeciesID = related.ID
	if o.R == nil {
		o.R = &petsPetR{
			Specy: related,
		}
	} else {
		o.R.Specy = related
	}

	if related.R == nil {
		related.R = &petsSpecyR{
			SpecyPetsPets: PetsPetSlice{o},
		}
	} else {
		related.R.SpecyPetsPets = append(related.R.SpecyPetsPets, o)
	}

	return nil
}

// PetsPets retrieves all the records using an executor.
func PetsPets(mods ...qm.QueryMod) petsPetQuery {
	mods = append(mods, qm.From("\"pets_pet\""))
	return petsPetQuery{NewQuery(mods...)}
}

// FindPetsPet retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPetsPet(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*PetsPet, error) {
	petsPetObj := &PetsPet{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"pets_pet\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, petsPetObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from pets_pet")
	}

	if err = petsPetObj.doAfterSelectHooks(ctx, exec); err != nil {
		return petsPetObj, err
	}

	return petsPetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PetsPet) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no pets_pet provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(petsPetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	petsPetInsertCacheMut.RLock()
	cache, cached := petsPetInsertCache[key]
	petsPetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			petsPetAllColumns,
			petsPetColumnsWithDefault,
			petsPetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(petsPetType, petsPetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(petsPetType, petsPetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"pets_pet\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"pets_pet\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into pets_pet")
	}

	if !cached {
		petsPetInsertCacheMut.Lock()
		petsPetInsertCache[key] = cache
		petsPetInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PetsPet.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PetsPet) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	petsPetUpdateCacheMut.RLock()
	cache, cached := petsPetUpdateCache[key]
	petsPetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			petsPetAllColumns,
			petsPetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update pets_pet, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"pets_pet\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, petsPetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(petsPetType, petsPetMapping, append(wl, petsPetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update pets_pet row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for pets_pet")
	}

	if !cached {
		petsPetUpdateCacheMut.Lock()
		petsPetUpdateCache[key] = cache
		petsPetUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q petsPetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for pets_pet")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for pets_pet")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PetsPetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), petsPetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"pets_pet\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, petsPetPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in petsPet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all petsPet")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PetsPet) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no pets_pet provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(petsPetColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	petsPetUpsertCacheMut.RLock()
	cache, cached := petsPetUpsertCache[key]
	petsPetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			petsPetAllColumns,
			petsPetColumnsWithDefault,
			petsPetColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			petsPetAllColumns,
			petsPetPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert pets_pet, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(petsPetPrimaryKeyColumns))
			copy(conflict, petsPetPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"pets_pet\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(petsPetType, petsPetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(petsPetType, petsPetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert pets_pet")
	}

	if !cached {
		petsPetUpsertCacheMut.Lock()
		petsPetUpsertCache[key] = cache
		petsPetUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PetsPet record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PetsPet) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PetsPet provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), petsPetPrimaryKeyMapping)
	sql := "DELETE FROM \"pets_pet\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from pets_pet")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for pets_pet")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q petsPetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no petsPetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from pets_pet")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for pets_pet")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PetsPetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(petsPetBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), petsPetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"pets_pet\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, petsPetPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from petsPet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for pets_pet")
	}

	if len(petsPetAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PetsPet) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPetsPet(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PetsPetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PetsPetSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), petsPetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"pets_pet\".* FROM \"pets_pet\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, petsPetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PetsPetSlice")
	}

	*o = slice

	return nil
}

// PetsPetExists checks if the PetsPet row exists.
func PetsPetExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"pets_pet\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if pets_pet exists")
	}

	return exists, nil
}
