// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPetsSpecies(t *testing.T) {
	t.Parallel()

	query := PetsSpecies()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPetsSpeciesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPetsSpeciesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PetsSpecies().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPetsSpeciesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PetsSpecySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPetsSpeciesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PetsSpecyExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PetsSpecy exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PetsSpecyExists to return true, but got false.")
	}
}

func testPetsSpeciesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	petsSpecyFound, err := FindPetsSpecy(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if petsSpecyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPetsSpeciesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PetsSpecies().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPetsSpeciesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PetsSpecies().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPetsSpeciesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	petsSpecyOne := &PetsSpecy{}
	petsSpecyTwo := &PetsSpecy{}
	if err = randomize.Struct(seed, petsSpecyOne, petsSpecyDBTypes, false, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}
	if err = randomize.Struct(seed, petsSpecyTwo, petsSpecyDBTypes, false, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = petsSpecyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = petsSpecyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PetsSpecies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPetsSpeciesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	petsSpecyOne := &PetsSpecy{}
	petsSpecyTwo := &PetsSpecy{}
	if err = randomize.Struct(seed, petsSpecyOne, petsSpecyDBTypes, false, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}
	if err = randomize.Struct(seed, petsSpecyTwo, petsSpecyDBTypes, false, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = petsSpecyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = petsSpecyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func petsSpecyBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func petsSpecyAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PetsSpecy) error {
	*o = PetsSpecy{}
	return nil
}

func testPetsSpeciesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PetsSpecy{}
	o := &PetsSpecy{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PetsSpecy object: %s", err)
	}

	AddPetsSpecyHook(boil.BeforeInsertHook, petsSpecyBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	petsSpecyBeforeInsertHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.AfterInsertHook, petsSpecyAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	petsSpecyAfterInsertHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.AfterSelectHook, petsSpecyAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	petsSpecyAfterSelectHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.BeforeUpdateHook, petsSpecyBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	petsSpecyBeforeUpdateHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.AfterUpdateHook, petsSpecyAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	petsSpecyAfterUpdateHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.BeforeDeleteHook, petsSpecyBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	petsSpecyBeforeDeleteHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.AfterDeleteHook, petsSpecyAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	petsSpecyAfterDeleteHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.BeforeUpsertHook, petsSpecyBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	petsSpecyBeforeUpsertHooks = []PetsSpecyHook{}

	AddPetsSpecyHook(boil.AfterUpsertHook, petsSpecyAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	petsSpecyAfterUpsertHooks = []PetsSpecyHook{}
}

func testPetsSpeciesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPetsSpeciesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(petsSpecyColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPetsSpecyToManySpecyPetsPets(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PetsSpecy
	var b, c PetsPet

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, petsPetDBTypes, false, petsPetColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, petsPetDBTypes, false, petsPetColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.SpeciesID = a.ID
	c.SpeciesID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.SpecyPetsPets().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.SpeciesID == b.SpeciesID {
			bFound = true
		}
		if v.SpeciesID == c.SpeciesID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := PetsSpecySlice{&a}
	if err = a.L.LoadSpecyPetsPets(ctx, tx, false, (*[]*PetsSpecy)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SpecyPetsPets); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.SpecyPetsPets = nil
	if err = a.L.LoadSpecyPetsPets(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SpecyPetsPets); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testPetsSpecyToManyAddOpSpecyPetsPets(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PetsSpecy
	var b, c, d, e PetsPet

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, petsSpecyDBTypes, false, strmangle.SetComplement(petsSpecyPrimaryKeyColumns, petsSpecyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PetsPet{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, petsPetDBTypes, false, strmangle.SetComplement(petsPetPrimaryKeyColumns, petsPetColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*PetsPet{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSpecyPetsPets(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.SpeciesID {
			t.Error("foreign key was wrong value", a.ID, first.SpeciesID)
		}
		if a.ID != second.SpeciesID {
			t.Error("foreign key was wrong value", a.ID, second.SpeciesID)
		}

		if first.R.Specy != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Specy != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.SpecyPetsPets[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.SpecyPetsPets[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.SpecyPetsPets().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testPetsSpeciesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPetsSpeciesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PetsSpecySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPetsSpeciesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PetsSpecies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	petsSpecyDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`}
	_                = bytes.MinRead
)

func testPetsSpeciesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(petsSpecyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(petsSpecyAllColumns) == len(petsSpecyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPetsSpeciesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(petsSpecyAllColumns) == len(petsSpecyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PetsSpecy{}
	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, petsSpecyDBTypes, true, petsSpecyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(petsSpecyAllColumns, petsSpecyPrimaryKeyColumns) {
		fields = petsSpecyAllColumns
	} else {
		fields = strmangle.SetComplement(
			petsSpecyAllColumns,
			petsSpecyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PetsSpecySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPetsSpeciesUpsert(t *testing.T) {
	t.Parallel()

	if len(petsSpecyAllColumns) == len(petsSpecyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PetsSpecy{}
	if err = randomize.Struct(seed, &o, petsSpecyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PetsSpecy: %s", err)
	}

	count, err := PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, petsSpecyDBTypes, false, petsSpecyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PetsSpecy struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PetsSpecy: %s", err)
	}

	count, err = PetsSpecies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
