// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PetsSpecy is an object representing the database table.
type PetsSpecy struct {
	ID   int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *petsSpecyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L petsSpecyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PetsSpecyColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var PetsSpecyTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "pets_species.id",
	Name: "pets_species.name",
}

// Generated where

var PetsSpecyWhere = struct {
	ID   whereHelperint64
	Name whereHelperstring
}{
	ID:   whereHelperint64{field: "\"pets_species\".\"id\""},
	Name: whereHelperstring{field: "\"pets_species\".\"name\""},
}

// PetsSpecyRels is where relationship names are stored.
var PetsSpecyRels = struct {
	SpecyPetsPets string
}{
	SpecyPetsPets: "SpecyPetsPets",
}

// petsSpecyR is where relationships are stored.
type petsSpecyR struct {
	SpecyPetsPets PetsPetSlice `boil:"SpecyPetsPets" json:"SpecyPetsPets" toml:"SpecyPetsPets" yaml:"SpecyPetsPets"`
}

// NewStruct creates a new relationship struct
func (*petsSpecyR) NewStruct() *petsSpecyR {
	return &petsSpecyR{}
}

// petsSpecyL is where Load methods for each relationship are stored.
type petsSpecyL struct{}

var (
	petsSpecyAllColumns            = []string{"id", "name"}
	petsSpecyColumnsWithoutDefault = []string{"name"}
	petsSpecyColumnsWithDefault    = []string{"id"}
	petsSpecyPrimaryKeyColumns     = []string{"id"}
	petsSpecyGeneratedColumns      = []string{}
)

type (
	// PetsSpecySlice is an alias for a slice of pointers to PetsSpecy.
	// This should almost always be used instead of []PetsSpecy.
	PetsSpecySlice []*PetsSpecy
	// PetsSpecyHook is the signature for custom PetsSpecy hook methods
	PetsSpecyHook func(context.Context, boil.ContextExecutor, *PetsSpecy) error

	petsSpecyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	petsSpecyType                 = reflect.TypeOf(&PetsSpecy{})
	petsSpecyMapping              = queries.MakeStructMapping(petsSpecyType)
	petsSpecyPrimaryKeyMapping, _ = queries.BindMapping(petsSpecyType, petsSpecyMapping, petsSpecyPrimaryKeyColumns)
	petsSpecyInsertCacheMut       sync.RWMutex
	petsSpecyInsertCache          = make(map[string]insertCache)
	petsSpecyUpdateCacheMut       sync.RWMutex
	petsSpecyUpdateCache          = make(map[string]updateCache)
	petsSpecyUpsertCacheMut       sync.RWMutex
	petsSpecyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var petsSpecyAfterSelectHooks []PetsSpecyHook

var petsSpecyBeforeInsertHooks []PetsSpecyHook
var petsSpecyAfterInsertHooks []PetsSpecyHook

var petsSpecyBeforeUpdateHooks []PetsSpecyHook
var petsSpecyAfterUpdateHooks []PetsSpecyHook

var petsSpecyBeforeDeleteHooks []PetsSpecyHook
var petsSpecyAfterDeleteHooks []PetsSpecyHook

var petsSpecyBeforeUpsertHooks []PetsSpecyHook
var petsSpecyAfterUpsertHooks []PetsSpecyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PetsSpecy) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PetsSpecy) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PetsSpecy) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PetsSpecy) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PetsSpecy) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PetsSpecy) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PetsSpecy) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PetsSpecy) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PetsSpecy) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range petsSpecyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPetsSpecyHook registers your hook function for all future operations.
func AddPetsSpecyHook(hookPoint boil.HookPoint, petsSpecyHook PetsSpecyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		petsSpecyAfterSelectHooks = append(petsSpecyAfterSelectHooks, petsSpecyHook)
	case boil.BeforeInsertHook:
		petsSpecyBeforeInsertHooks = append(petsSpecyBeforeInsertHooks, petsSpecyHook)
	case boil.AfterInsertHook:
		petsSpecyAfterInsertHooks = append(petsSpecyAfterInsertHooks, petsSpecyHook)
	case boil.BeforeUpdateHook:
		petsSpecyBeforeUpdateHooks = append(petsSpecyBeforeUpdateHooks, petsSpecyHook)
	case boil.AfterUpdateHook:
		petsSpecyAfterUpdateHooks = append(petsSpecyAfterUpdateHooks, petsSpecyHook)
	case boil.BeforeDeleteHook:
		petsSpecyBeforeDeleteHooks = append(petsSpecyBeforeDeleteHooks, petsSpecyHook)
	case boil.AfterDeleteHook:
		petsSpecyAfterDeleteHooks = append(petsSpecyAfterDeleteHooks, petsSpecyHook)
	case boil.BeforeUpsertHook:
		petsSpecyBeforeUpsertHooks = append(petsSpecyBeforeUpsertHooks, petsSpecyHook)
	case boil.AfterUpsertHook:
		petsSpecyAfterUpsertHooks = append(petsSpecyAfterUpsertHooks, petsSpecyHook)
	}
}

// One returns a single petsSpecy record from the query.
func (q petsSpecyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PetsSpecy, error) {
	o := &PetsSpecy{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for pets_species")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PetsSpecy records from the query.
func (q petsSpecyQuery) All(ctx context.Context, exec boil.ContextExecutor) (PetsSpecySlice, error) {
	var o []*PetsSpecy

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PetsSpecy slice")
	}

	if len(petsSpecyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PetsSpecy records in the query.
func (q petsSpecyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count pets_species rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q petsSpecyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if pets_species exists")
	}

	return count > 0, nil
}

// SpecyPetsPets retrieves all the pets_pet's PetsPets with an executor via species_id column.
func (o *PetsSpecy) SpecyPetsPets(mods ...qm.QueryMod) petsPetQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"pets_pet\".\"species_id\"=?", o.ID),
	)

	query := PetsPets(queryMods...)
	queries.SetFrom(query.Query, "\"pets_pet\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"pets_pet\".*"})
	}

	return query
}

// LoadSpecyPetsPets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (petsSpecyL) LoadSpecyPetsPets(ctx context.Context, e boil.ContextExecutor, singular bool, maybePetsSpecy interface{}, mods queries.Applicator) error {
	var slice []*PetsSpecy
	var object *PetsSpecy

	if singular {
		object = maybePetsSpecy.(*PetsSpecy)
	} else {
		slice = *maybePetsSpecy.(*[]*PetsSpecy)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &petsSpecyR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &petsSpecyR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`pets_pet`),
		qm.WhereIn(`pets_pet.species_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load pets_pet")
	}

	var resultSlice []*PetsPet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice pets_pet")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on pets_pet")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for pets_pet")
	}

	if len(petsPetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SpecyPetsPets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &petsPetR{}
			}
			foreign.R.Specy = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SpeciesID {
				local.R.SpecyPetsPets = append(local.R.SpecyPetsPets, foreign)
				if foreign.R == nil {
					foreign.R = &petsPetR{}
				}
				foreign.R.Specy = local
				break
			}
		}
	}

	return nil
}

// AddSpecyPetsPets adds the given related objects to the existing relationships
// of the pets_specy, optionally inserting them as new records.
// Appends related to o.R.SpecyPetsPets.
// Sets related.R.Specy appropriately.
func (o *PetsSpecy) AddSpecyPetsPets(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PetsPet) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SpeciesID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"pets_pet\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"species_id"}),
				strmangle.WhereClause("\"", "\"", 2, petsPetPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SpeciesID = o.ID
		}
	}

	if o.R == nil {
		o.R = &petsSpecyR{
			SpecyPetsPets: related,
		}
	} else {
		o.R.SpecyPetsPets = append(o.R.SpecyPetsPets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &petsPetR{
				Specy: o,
			}
		} else {
			rel.R.Specy = o
		}
	}
	return nil
}

// PetsSpecies retrieves all the records using an executor.
func PetsSpecies(mods ...qm.QueryMod) petsSpecyQuery {
	mods = append(mods, qm.From("\"pets_species\""))
	return petsSpecyQuery{NewQuery(mods...)}
}

// FindPetsSpecy retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPetsSpecy(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*PetsSpecy, error) {
	petsSpecyObj := &PetsSpecy{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"pets_species\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, petsSpecyObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from pets_species")
	}

	if err = petsSpecyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return petsSpecyObj, err
	}

	return petsSpecyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PetsSpecy) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no pets_species provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(petsSpecyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	petsSpecyInsertCacheMut.RLock()
	cache, cached := petsSpecyInsertCache[key]
	petsSpecyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			petsSpecyAllColumns,
			petsSpecyColumnsWithDefault,
			petsSpecyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(petsSpecyType, petsSpecyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(petsSpecyType, petsSpecyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"pets_species\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"pets_species\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into pets_species")
	}

	if !cached {
		petsSpecyInsertCacheMut.Lock()
		petsSpecyInsertCache[key] = cache
		petsSpecyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PetsSpecy.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PetsSpecy) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	petsSpecyUpdateCacheMut.RLock()
	cache, cached := petsSpecyUpdateCache[key]
	petsSpecyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			petsSpecyAllColumns,
			petsSpecyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update pets_species, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"pets_species\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, petsSpecyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(petsSpecyType, petsSpecyMapping, append(wl, petsSpecyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update pets_species row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for pets_species")
	}

	if !cached {
		petsSpecyUpdateCacheMut.Lock()
		petsSpecyUpdateCache[key] = cache
		petsSpecyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q petsSpecyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for pets_species")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for pets_species")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PetsSpecySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), petsSpecyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"pets_species\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, petsSpecyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in petsSpecy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all petsSpecy")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PetsSpecy) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no pets_species provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(petsSpecyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	petsSpecyUpsertCacheMut.RLock()
	cache, cached := petsSpecyUpsertCache[key]
	petsSpecyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			petsSpecyAllColumns,
			petsSpecyColumnsWithDefault,
			petsSpecyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			petsSpecyAllColumns,
			petsSpecyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert pets_species, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(petsSpecyPrimaryKeyColumns))
			copy(conflict, petsSpecyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"pets_species\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(petsSpecyType, petsSpecyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(petsSpecyType, petsSpecyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert pets_species")
	}

	if !cached {
		petsSpecyUpsertCacheMut.Lock()
		petsSpecyUpsertCache[key] = cache
		petsSpecyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PetsSpecy record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PetsSpecy) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PetsSpecy provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), petsSpecyPrimaryKeyMapping)
	sql := "DELETE FROM \"pets_species\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from pets_species")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for pets_species")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q petsSpecyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no petsSpecyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from pets_species")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for pets_species")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PetsSpecySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(petsSpecyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), petsSpecyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"pets_species\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, petsSpecyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from petsSpecy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for pets_species")
	}

	if len(petsSpecyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PetsSpecy) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPetsSpecy(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PetsSpecySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PetsSpecySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), petsSpecyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"pets_species\".* FROM \"pets_species\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, petsSpecyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PetsSpecySlice")
	}

	*o = slice

	return nil
}

// PetsSpecyExists checks if the PetsSpecy row exists.
func PetsSpecyExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"pets_species\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if pets_species exists")
	}

	return exists, nil
}
